#!/usr/bin/env node
/**
 * VietnamDentalTravel Landing Page Builder
 * ========================================
 * Reads HTML files from pages/vietnamdentaltravel/ subfolders and bundles them
 * into worker-dental.js with path-based routing for Cloudflare Workers.
 *
 * Usage: node build-dental.js
 *
 * Structure expected:
 *   pages/vietnamdentaltravel/dental-implants-vietnam/index.html → served at /dental-implants-vietnam
 *
 * Output: worker-dental.js (ready to deploy via wrangler-dental.toml)
 */

const fs = require('fs');
const path = require('path');

const PAGES_DIR = path.join(__dirname, 'pages', 'vietnamdentaltravel');
const OUTPUT_FILE = path.join(__dirname, 'worker-dental.js');

// Landing page config: folder name → route path
const PAGES_CONFIG = {
  'dental-implants-vietnam': { path: '/dental-implants-vietnam', isDefault: true, name: 'Dental Implants Vietnam — Save 70% vs Australia' },
};

function readPageHTML(folderName) {
  const htmlPath = path.join(PAGES_DIR, folderName, 'index.html');
  if (!fs.existsSync(htmlPath)) {
    console.warn(`  ⚠ Skipping "${folderName}" — no index.html found`);
    return null;
  }
  const content = fs.readFileSync(htmlPath, 'utf-8');
  console.log(`  ✓ ${folderName} (${(content.length / 1024).toFixed(1)} KB)`);
  return content;
}

function escapeTemplateLiteral(str) {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function build() {
  console.log('🦷 VietnamDentalTravel Landing Page Builder');
  console.log('============================================\n');
  console.log('Reading pages:');

  const pages = {};
  let defaultPage = null;

  for (const [folder, config] of Object.entries(PAGES_CONFIG)) {
    const html = readPageHTML(folder);
    if (html) {
      pages[folder] = { ...config, html };
      if (config.isDefault) defaultPage = folder;
    }
  }

  // Also scan for any new folders not in config
  if (fs.existsSync(PAGES_DIR)) {
    const dirs = fs.readdirSync(PAGES_DIR, { withFileTypes: true })
      .filter(d => d.isDirectory())
      .map(d => d.name);

    for (const dir of dirs) {
      if (!PAGES_CONFIG[dir]) {
        const html = readPageHTML(dir);
        if (html) {
          pages[dir] = { path: `/${dir}`, name: dir, html };
          console.log(`  + Auto-discovered: ${dir} → /${dir}`);
        }
      }
    }
  }

  const pageCount = Object.keys(pages).length;
  console.log(`\n📄 ${pageCount} pages loaded\n`);

  if (pageCount === 0) {
    console.error('❌ No pages found! Make sure pages/vietnamdentaltravel/ folder has subfolders with index.html');
    process.exit(1);
  }

  // Generate worker-dental.js
  let workerCode = `// Auto-generated by build-dental.js — DO NOT EDIT DIRECTLY
// Edit HTML files in pages/vietnamdentaltravel/ subfolders, then run: node build-dental.js
// Generated: ${new Date().toISOString()}
// Pages: ${pageCount}

`;

  // Add each page as a constant
  for (const [folder, page] of Object.entries(pages)) {
    const varName = `PAGE_${folder.replace(/-/g, '_').toUpperCase()}`;
    workerCode += `const ${varName} = \`${escapeTemplateLiteral(page.html)}\`;\n\n`;
  }

  // Build route map
  workerCode += `// Route map: path → HTML content\nconst ROUTES = {\n`;
  for (const [folder, page] of Object.entries(pages)) {
    const varName = `PAGE_${folder.replace(/-/g, '_').toUpperCase()}`;
    workerCode += `  '${page.path}': ${varName},\n`;
  }
  workerCode += `};\n\n`;

  // Add the default page reference (for redirect)
  if (defaultPage) {
    const defaultVar = `PAGE_${defaultPage.replace(/-/g, '_').toUpperCase()}`;
    workerCode += `const DEFAULT_PAGE = ${defaultVar};\n`;
    workerCode += `const DEFAULT_PATH = '${pages[defaultPage].path}';\n\n`;
  }

  // Generate 404 page with VietnamDentalTravel branding and teal color scheme
  workerCode += `const PAGE_404 = \`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Page Not Found | VietnamDentalTravel</title>
  <style>
    body{font-family:'Inter',system-ui,sans-serif;display:flex;justify-content:center;align-items:center;min-height:100vh;background:#F9FAFB;color:#1A1A1A;text-align:center}
    .container{max-width:500px;padding:2rem}
    h1{font-size:3rem;color:#0F6E56;margin-bottom:1rem;font-weight:800}
    p{margin-bottom:1.5rem;color:#6B7280}
    a{color:#0F6E56;text-decoration:none;font-weight:600}
    a:hover{text-decoration:underline}
    .tours{text-align:left;margin:2rem 0}
    .tours a{display:block;padding:0.75rem 1rem;margin:0.5rem 0;background:#fff;border-radius:8px;border:1px solid #E5E7EB;transition:all 0.2s}
    .tours a:hover{border-color:#0F6E56;transform:translateX(4px);text-decoration:none}
  </style>
</head>
<body>
  <div class="container">
    <h1>404</h1>
    <p>This page doesn't exist. Explore our dental travel services below:</p>
    <div class="tours">
`;

  // Add links to all pages in 404
  for (const [folder, page] of Object.entries(pages)) {
    workerCode += `      <a href="${page.path}">${page.name || folder}</a>\n`;
  }

  workerCode += `    </div>
  </div>
</body>
</html>\`;\n\n`;

  // Add sitemap generator with vietnamdentaltravel.com base
  workerCode += `function generateSitemap(baseUrl) {
  const urls = Object.keys(ROUTES).map(path => {
    return \`  <url>
    <loc>\${baseUrl}\${path === '/' ? '' : path}</loc>
    <changefreq>weekly</changefreq>
    <priority>\${path === '/' ? '1.0' : '0.8'}</priority>
  </url>\`;
  }).join('\\n');

  return \`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
\${urls}
</urlset>\`;
}\n\n`;

  // Add robots.txt generator
  workerCode += `function generateRobotsTxt() {
  return \`User-agent: *
Allow: /

Sitemap: https://vietnamdentaltravel.com/sitemap.xml\`;
}\n\n`;

  // Fetch handler with routing — includes 301 redirect from / to /dental-implants-vietnam
  workerCode += `export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const pathname = url.pathname.replace(/\\/+$/, '') || '/';
    const baseUrl = 'https://vietnamdentaltravel.com';

    // Favicon
    if (pathname === '/favicon.ico') {
      return new Response(null, { status: 204 });
    }

    // Sitemap
    if (pathname === '/sitemap.xml') {
      return new Response(generateSitemap(baseUrl), {
        headers: {
          'Content-Type': 'application/xml;charset=UTF-8',
          'Cache-Control': 'public, max-age=86400',
        },
      });
    }

    // Robots.txt
    if (pathname === '/robots.txt') {
      return new Response(generateRobotsTxt(), {
        headers: {
          'Content-Type': 'text/plain;charset=UTF-8',
          'Cache-Control': 'public, max-age=86400',
        },
      });
    }

    // Root redirect: / → /dental-implants-vietnam (301)
    if (pathname === '/') {
      return Response.redirect(\`\${baseUrl}\${DEFAULT_PATH}\`, 301);
    }

    // Route to the correct landing page
    const html = ROUTES[pathname];
    if (html) {
      return new Response(html, {
        headers: {
          'Content-Type': 'text/html;charset=UTF-8',
          'Cache-Control': 'public, max-age=3600',
          'Access-Control-Allow-Origin': '*',
          'X-Content-Type-Options': 'nosniff',
          'X-Frame-Options': 'DENY',
        },
      });
    }

    // 404 for unmatched routes
    return new Response(PAGE_404, {
      status: 404,
      headers: {
        'Content-Type': 'text/html;charset=UTF-8',
        'Cache-Control': 'no-cache',
      },
    });
  },
};
`;

  // Write output
  fs.writeFileSync(OUTPUT_FILE, workerCode);
  const outputSize = (fs.statSync(OUTPUT_FILE).size / 1024).toFixed(1);
  console.log(`✅ worker-dental.js generated (${outputSize} KB)`);
  console.log('\nRoutes:');
  console.log(`  / → 301 redirect → /dental-implants-vietnam`);
  for (const [folder, page] of Object.entries(pages)) {
    workerCode += '';
    console.log(`  ${page.path} → ${page.name}`);
  }
  console.log(`\n🚀 Ready to deploy: npx wrangler deploy --config wrangler-dental.toml`);
}

build();
