// Auto-generated by build-dental.js — DO NOT EDIT DIRECTLY
// Edit HTML files in pages/vietnamdentaltravel/ subfolders, then run: node build-dental.js
// Generated: 2026-04-13T08:28:16.579Z
// Pages: 1

const PAGE_DENTAL_IMPLANTS_VIETNAM = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Primary SEO -->
  <title>Dental Implants Vietnam 2026 | Save 70% vs Australia — From $700</title>
  <meta name="description" content="Get dental implants in Vietnam from $700. Same Straumann & Nobel Biocare brands. 97.8% success rate. Free treatment plan in 24hrs.">
  <meta name="keywords" content="dental implants Vietnam, dental implants Vietnam cost, dental tourism Vietnam, dental implants abroad, cheap dental implants Vietnam, Vietnam dentist, Straumann implants Vietnam, Nobel Biocare Vietnam, dental holiday Vietnam, dental travel Vietnam, dental implants Ho Chi Minh City, dental implants Hanoi, Vietnam dental clinic, dental implant package Vietnam, save on dental implants, dental implants from Australia, dental tourism from Australia, affordable dental implants, all on 4 Vietnam, full mouth dental implants Vietnam, dental crown Vietnam, veneer Vietnam, VietnamDentalTravel">
  <link rel="canonical" href="https://vietnamdentaltravel.com/dental-implants-vietnam">

  <!-- Open Graph -->
  <meta property="og:type" content="website">
  <meta property="og:title" content="Dental Implants Vietnam 2026 | Save 70% vs Australia — From $700">
  <meta property="og:description" content="Get dental implants in Vietnam from $700. Same Straumann & Nobel Biocare brands. 97.8% success rate. Free treatment plan in 24hrs.">
  <meta property="og:url" content="https://vietnamdentaltravel.com/dental-implants-vietnam">
  <meta property="og:site_name" content="VietnamDentalTravel">
  <meta property="og:locale" content="en_AU">
  <meta property="og:image" content="https://vietnamdentaltravel.com/images/og-dental-implants-vietnam.jpg">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">

  <!-- Twitter Card -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="Dental Implants Vietnam 2026 | Save 70% vs Australia — From $700">
  <meta name="twitter:description" content="Get dental implants in Vietnam from $700. Same Straumann & Nobel Biocare brands. 97.8% success rate. Free treatment plan in 24hrs.">
  <meta name="twitter:image" content="https://vietnamdentaltravel.com/images/og-dental-implants-vietnam.jpg">

  <!-- Hreflang -->
  <link rel="alternate" hreflang="en-AU" href="https://vietnamdentaltravel.com/dental-implants-vietnam">
  <link rel="alternate" hreflang="en-US" href="https://vietnamdentaltravel.com/dental-implants-vietnam">
  <link rel="alternate" hreflang="en-GB" href="https://vietnamdentaltravel.com/dental-implants-vietnam">
  <link rel="alternate" hreflang="x-default" href="https://vietnamdentaltravel.com/dental-implants-vietnam">

  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-TPQWV864');</script>

  <!-- GA4 -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-LKDCCNJMP3"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-LKDCCNJMP3');
    gtag('config', 'AW-17709107883');
  </script>

  <!-- Facebook Pixel -->
  <script>
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '579298288600609');
    fbq('track', 'PageView');
  </script>
  <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=579298288600609&ev=PageView&noscript=1"></noscript>

  <!-- Favicon -->
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🦷</text></svg>">

  <style>
    /* ===== CSS Variables ===== */
    :root {
      --primary: #0F6E56;
      --primary-dark: #0A5A45;
      --accent: #1D9E75;
      --highlight: #D85A30;
      --highlight-dark: #C04A20;
      --bg: #FFFFFF;
      --bg-alt: #F9FAFB;
      --text: #1A1A1A;
      --text-muted: #6B7280;
      --border: #E5E7EB;
      --radius: 12px;
      --shadow: 0 1px 3px rgba(0,0,0,0.1);
      --shadow-lg: 0 10px 40px rgba(0,0,0,0.12);
    }

    /* ===== Reset & Base ===== */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { scroll-behavior: smooth; -webkit-text-size-adjust: 100%; }
    body {
      font-family: 'Inter', system-ui, -apple-system, sans-serif;
      color: var(--text);
      background: var(--bg);
      line-height: 1.6;
      -webkit-font-smoothing: antialiased;
    }
    img { max-width: 100%; height: auto; display: block; }
    a { color: var(--primary); text-decoration: none; }
    a:hover { text-decoration: underline; }

    /* ===== Layout ===== */
    .container { max-width: 1200px; margin: 0 auto; padding: 0 1.5rem; }
    section { padding: 4rem 0; }
    section:nth-child(even) { background: var(--bg-alt); }

    /* ===== Typography ===== */
    h1 { font-size: 2.5rem; font-weight: 800; line-height: 1.2; }
    h2 { font-size: 2rem; font-weight: 700; line-height: 1.3; margin-bottom: 1rem; }
    h3 { font-size: 1.25rem; font-weight: 600; line-height: 1.4; }
    p { margin-bottom: 1rem; }

    /* ===== Buttons ===== */
    .btn {
      display: inline-block;
      padding: 0.875rem 2rem;
      border-radius: var(--radius);
      font-weight: 700;
      font-size: 1rem;
      cursor: pointer;
      transition: all 0.2s;
      border: none;
      text-align: center;
    }
    .btn-primary {
      background: var(--highlight);
      color: #fff;
    }
    .btn-primary:hover {
      background: var(--highlight-dark);
      text-decoration: none;
      transform: translateY(-1px);
      box-shadow: var(--shadow-lg);
    }
    .btn-outline {
      background: transparent;
      color: var(--primary);
      border: 2px solid var(--primary);
    }
    .btn-outline:hover {
      background: var(--primary);
      color: #fff;
      text-decoration: none;
    }

    /* ===== Responsive ===== */
    @media (max-width: 768px) {
      h1 { font-size: 1.75rem; }
      h2 { font-size: 1.5rem; }
      section { padding: 3rem 0; }
      .container { padding: 0 1rem; }
    }

    /* ===== Utility ===== */
    .text-center { text-align: center; }
    .text-muted { color: var(--text-muted); }
    .sr-only { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0; }
  </style>
</head>
<body>
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TPQWV864"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

  <!-- SECTION 1: HERO -->
  <section id="hero">
    <div class="container">
      <!-- Hero content: headline, price, CTA -->
    </div>
  </section>

  <!-- SECTION 2: SOCIAL PROOF -->
  <section id="social-proof">
    <div class="container">
      <!-- Trust badges, stats, partner logos -->
    </div>
  </section>

  <!-- SECTION 3: COST TABLE -->
  <section id="cost-comparison">
    <div class="container">
      <!-- Australia vs Vietnam price comparison table -->
    </div>
  </section>

  <!-- SECTION 4: TIMELINE -->
  <section id="timeline">
    <div class="container">
      <!-- Treatment timeline / how it works -->
    </div>
  </section>

  <!-- SECTION 5: BRANDS -->
  <section id="brands">
    <div class="container">
      <!-- Straumann, Nobel Biocare, Osstem logos & info -->
    </div>
  </section>

  <!-- SECTION 6: CLINICS -->
  <section id="clinics">
    <div class="container">
      <!-- Partner clinic profiles -->
    </div>
  </section>

  <!-- SECTION 7: TESTIMONIALS -->
  <section id="testimonials">
    <div class="container">
      <!-- Patient reviews & before/after -->
    </div>
  </section>

  <!-- SECTION 8: SAFETY -->
  <section id="safety">
    <div class="container">
      <!-- Safety standards, certifications, guarantees -->
    </div>
  </section>

  <!-- SECTION 9: FAQ -->
  <section id="faq">
    <div class="container">
      <!-- Frequently asked questions -->
    </div>
  </section>

  <!-- SECTION 10: FORM -->
  <section id="booking-form">
    <div class="container">
      <!-- Booking / enquiry form (Web3Forms) -->
    </div>
  </section>

  <!-- FLOATING ELEMENTS -->
  <!-- WhatsApp button, sticky CTA bar, back-to-top — placeholder -->

  <!-- SCHEMA.ORG JSON-LD -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "MedicalBusiness",
        "name": "VietnamDentalTravel",
        "url": "https://vietnamdentaltravel.com",
        "description": "Premium dental tourism service connecting Australian patients with top-rated dental clinics in Vietnam."
      },
      {
        "@type": "FAQPage",
        "mainEntity": []
      },
      {
        "@type": "BreadcrumbList",
        "itemListElement": [
          {
            "@type": "ListItem",
            "position": 1,
            "name": "Home",
            "item": "https://vietnamdentaltravel.com"
          },
          {
            "@type": "ListItem",
            "position": 2,
            "name": "Dental Implants Vietnam",
            "item": "https://vietnamdentaltravel.com/dental-implants-vietnam"
          }
        ]
      }
    ]
  }
  </script>
</body>
</html>
`;

// Route map: path → HTML content
const ROUTES = {
  '/dental-implants-vietnam': PAGE_DENTAL_IMPLANTS_VIETNAM,
};

const DEFAULT_PAGE = PAGE_DENTAL_IMPLANTS_VIETNAM;
const DEFAULT_PATH = '/dental-implants-vietnam';

const PAGE_404 = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Page Not Found | VietnamDentalTravel</title>
  <style>
    body{font-family:'Inter',system-ui,sans-serif;display:flex;justify-content:center;align-items:center;min-height:100vh;background:#F9FAFB;color:#1A1A1A;text-align:center}
    .container{max-width:500px;padding:2rem}
    h1{font-size:3rem;color:#0F6E56;margin-bottom:1rem;font-weight:800}
    p{margin-bottom:1.5rem;color:#6B7280}
    a{color:#0F6E56;text-decoration:none;font-weight:600}
    a:hover{text-decoration:underline}
    .tours{text-align:left;margin:2rem 0}
    .tours a{display:block;padding:0.75rem 1rem;margin:0.5rem 0;background:#fff;border-radius:8px;border:1px solid #E5E7EB;transition:all 0.2s}
    .tours a:hover{border-color:#0F6E56;transform:translateX(4px);text-decoration:none}
  </style>
</head>
<body>
  <div class="container">
    <h1>404</h1>
    <p>This page doesn't exist. Explore our dental travel services below:</p>
    <div class="tours">
      <a href="/dental-implants-vietnam">Dental Implants Vietnam — Save 70% vs Australia</a>
    </div>
  </div>
</body>
</html>`;

function generateSitemap(baseUrl) {
  const urls = Object.keys(ROUTES).map(path => {
    return `  <url>
    <loc>${baseUrl}${path === '/' ? '' : path}</loc>
    <changefreq>weekly</changefreq>
    <priority>${path === '/' ? '1.0' : '0.8'}</priority>
  </url>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;
}

function generateRobotsTxt() {
  return `User-agent: *
Allow: /

Sitemap: https://vietnamdentaltravel.com/sitemap.xml`;
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const pathname = url.pathname.replace(/\/+$/, '') || '/';
    const baseUrl = 'https://vietnamdentaltravel.com';

    // Favicon
    if (pathname === '/favicon.ico') {
      return new Response(null, { status: 204 });
    }

    // Sitemap
    if (pathname === '/sitemap.xml') {
      return new Response(generateSitemap(baseUrl), {
        headers: {
          'Content-Type': 'application/xml;charset=UTF-8',
          'Cache-Control': 'public, max-age=86400',
        },
      });
    }

    // Robots.txt
    if (pathname === '/robots.txt') {
      return new Response(generateRobotsTxt(), {
        headers: {
          'Content-Type': 'text/plain;charset=UTF-8',
          'Cache-Control': 'public, max-age=86400',
        },
      });
    }

    // Root redirect: / → /dental-implants-vietnam (301)
    if (pathname === '/') {
      return Response.redirect(`${baseUrl}${DEFAULT_PATH}`, 301);
    }

    // Route to the correct landing page
    const html = ROUTES[pathname];
    if (html) {
      return new Response(html, {
        headers: {
          'Content-Type': 'text/html;charset=UTF-8',
          'Cache-Control': 'public, max-age=3600',
          'Access-Control-Allow-Origin': '*',
          'X-Content-Type-Options': 'nosniff',
          'X-Frame-Options': 'DENY',
        },
      });
    }

    // 404 for unmatched routes
    return new Response(PAGE_404, {
      status: 404,
      headers: {
        'Content-Type': 'text/html;charset=UTF-8',
        'Cache-Control': 'no-cache',
      },
    });
  },
};
