#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Scope: enable a Cloudflare Rate limiting rule on POST /api/lead across both
# zones (myvivatour.com, vietnamdentaltravel.com) — threshold locked by Minh
# on 260812: 10 requests/minute/IP, action Block (→ 429). This is a WAF-layer
# guard; it does NOT replace the app-layer limits already in
# worker-modules/lead-ingest-handler.js (32KB body / 40 keys / honeypot /
# host allowlist) — this wizard only tells you what to click, it never calls
# the Cloudflare API and never needs a token.
#
# Resume: progress is tracked in $CF_RL_STATE_FILE (default:
# .cf-ratelimit-wizard-state, gitignored-safe dotfile in repo root).
# Re-running the script offers to skip any stage already marked done. Rule
# IDs from both zones are written to $CF_RL_RESULT_FILE (default:
# cf-ratelimit-result.txt) for NT1 to read back.

TOTAL_STAGES=5

CF_RL_STATE_FILE="${CF_RL_STATE_FILE:-.cf-ratelimit-wizard-state}"
CF_RL_RESULT_FILE="${CF_RL_RESULT_FILE:-cf-ratelimit-result.txt}"

# _is_done ID — true if stage ID was previously marked complete.
_is_done() {
  [[ -f "$CF_RL_STATE_FILE" ]] && grep -qx "$1" "$CF_RL_STATE_FILE"
}

# _mark_done ID — record stage ID as complete (idempotent).
_mark_done() {
  touch "$CF_RL_STATE_FILE"
  _is_done "$1" || printf '%s\n' "$1" >> "$CF_RL_STATE_FILE"
}

# write_result KEY VALUE — upsert KEY=VALUE into CF_RL_RESULT_FILE. Separate
# from write_env/.env on purpose: this is a hand-off artifact for NT1, not a
# secret or local-dev config value.
write_result() {
  local key="$1" value="$2" tmp
  touch "$CF_RL_RESULT_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$CF_RL_RESULT_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$CF_RL_RESULT_FILE"
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$CF_RL_RESULT_FILE"
}

# run_stage ID "Title" fn — run stage fn unless already marked done (asks
# before re-running); offers to mark done afterwards so a re-run can resume
# past it. ID must be stable across edits (used as the resume key).
run_stage() {
  local id="$1" title="$2" fn="$3"
  if _is_done "$id"; then
    _clear
    printf '\n%s%s▸ Stage %s · %s %s(đã đánh dấu XONG lần trước)%s\n' \
      "$BOLD" "$BLUE" "$id" "$title" "$DIM" "$RESET"
    if ! confirm "Chạy lại stage này?"; then
      note "Bỏ qua — đã xong lần trước."
      return 0
    fi
  fi
  "$fn"
  if confirm "Đã hoàn tất '$title'? (Y = đánh dấu xong để lần sau resume bỏ qua)"; then
    _mark_done "$id"
  else
    note "Chưa đánh dấu xong — lần chạy tới sẽ hỏi lại stage này."
  fi
}

CF_DASH_URL="https://dash.cloudflare.com/"
ESCAPE_URL="https://escape.myvivatour.com/api/lead"
DENTAL_URL="https://implant.vietnamdentaltravel.com/api/lead"
LP_FORM_URL="https://escape.myvivatour.com/"

banner "Cloudflare Rate limiting cho /api/lead"
say "Ngưỡng đã chốt: 10 request / 1 phút / mỗi IP trên POST /api/lead → vượt ngưỡng trả 429."
say "5 stage: bối cảnh, zone myvivatour.com, zone vietnamdentaltravel.com, test 429 bằng curl, test hồi quy form thật."
warn "Rule này KHÔNG thay app-layer limit trong worker-modules/lead-ingest-handler.js (32KB/40 keys/honeypot/host allowlist)."
warn "— đừng tạo thêm rule WAF nào lặp lại mấy giới hạn đó."

# ── Stage 1: Bối cảnh & lý do ngưỡng ────────────────────────────────────────
stage_01_context() {
  stage "Bối cảnh — ngưỡng 10/phút/IP và vì sao rộng tay"
  say "Ngưỡng: 10 request/phút/IP, match POST + path /api/lead, action Block → CF trả 429 tại edge."
  say "Lý do rộng tay: chặn nhầm khách thật = MẤT LEAD, đắt hơn nhiều so với lọt vài request spam."
  say "Khách thật có thể submit lại 2-3 lần khi sửa lỗi nhập liệu; văn phòng/quán dùng chung IP NAT"
  say "càng dễ cộng dồn nhiều khách thành 1 IP → đừng hạ ngưỡng xuống thấp hơn 10 mà không hỏi Minh."
  note "Code đã có giới hạn tầng app (worker-modules/lead-ingest-handler.js): body ≤32KB, ≤40 key,"
  note "honeypot botcheck/_gotcha, host allowlist. Rule Cloudflare ở đây CHỈ thêm rate limiting theo IP —"
  note "đừng dựng thêm rule WAF nào kiểm tra size/field, sẽ trùng và khó bảo trì."
  pause "Đã hiểu ngưỡng + lý do, sẵn sàng vào Cloudflare dashboard?"
}

# ── Stage 2: Zone 1 — myvivatour.com ────────────────────────────────────────
stage_02_zone_myvivatour() {
  stage "Zone 1: myvivatour.com — tạo Rate limiting rule"
  say "Áp cho host escape.myvivatour.com và happytours.myvivatour.com (cùng 1 rule ở cấp zone là đủ,"
  say "vì cả 2 host share zone myvivatour.com)."
  open_url "$CF_DASH_URL"
  step "Chọn đúng zone myvivatour.com (nếu tài khoản có nhiều zone, xác nhận domain trước khi vào)."
  step "Vào Security → WAF → Rate limiting rules → Create rule."
  step "Rule name: đặt tên rõ nghĩa, ví dụ 'lead-ingest-rate-limit'."
  step "Field matching request: If incoming requests match → chọn Custom filter expression, nhập:"
  note '  (http.request.uri.path eq "/api/lead" and http.request.method eq "POST")'
  step "When rate exceeds → Requests = 10, Period = 1 minute."
  step "With the same characteristics → chọn characteristic = IP Address (IP source, không phải IP + User-Agent)."
  step "Then → Action = Block (mặc định, trả 429 cho khách vượt ngưỡng)."
  note "Trade-off: Managed Challenge sẽ mềm hơn (khách thật gõ captcha vẫn qua được) nhưng KHÔNG trả 429 sạch"
  note "cho test bằng curl và làm phức tạp form flow. Mặc định dùng Block trừ khi Minh yêu cầu đổi."
  step "Duration/Timeout of block (nếu dashboard hỏi) → để mặc định (thường 10s hoặc 1 phút) là đủ, không cần chỉnh."
  step "Deploy / Save rule."
  step "Sau khi lưu, mở lại rule vừa tạo, copy Rule ID hiển thị trên trang chi tiết (hoặc trong URL)."
  ask CF_RULE_ID_MYVIVATOUR "Nhập Rule ID vừa tạo cho zone myvivatour.com:"
  write_result "CF_RULE_ID_MYVIVATOUR" "$CF_RULE_ID_MYVIVATOUR"
  write_result "CF_RULE_ZONE_MYVIVATOUR_HOSTS" "escape.myvivatour.com,happytours.myvivatour.com"
}

# ── Stage 3: Zone 2 — vietnamdentaltravel.com ───────────────────────────────
stage_03_zone_dental() {
  stage "Zone 2: vietnamdentaltravel.com — tạo Rate limiting rule"
  say "Zone riêng (khác myvivatour.com), áp cho host implant.vietnamdentaltravel.com."
  open_url "$CF_DASH_URL"
  step "Chọn đúng zone vietnamdentaltravel.com."
  step "Vào Security → WAF → Rate limiting rules → Create rule."
  step "Rule name: ví dụ 'lead-ingest-rate-limit' (giống tên zone 1 cho dễ nhận diện)."
  step "Field matching request: Custom filter expression, nhập ĐÚNG như zone 1:"
  note '  (http.request.uri.path eq "/api/lead" and http.request.method eq "POST")'
  step "When rate exceeds → Requests = 10, Period = 1 minute."
  step "With the same characteristics → characteristic = IP Address."
  step "Then → Action = Block (mặc định → 429). Duration để mặc định."
  step "Deploy / Save rule."
  step "Sau khi lưu, mở lại rule vừa tạo, copy Rule ID."
  ask CF_RULE_ID_DENTAL "Nhập Rule ID vừa tạo cho zone vietnamdentaltravel.com:"
  write_result "CF_RULE_ID_DENTAL" "$CF_RULE_ID_DENTAL"
  write_result "CF_RULE_ZONE_DENTAL_HOSTS" "implant.vietnamdentaltravel.com"
}

# ── Stage 4: Test vượt ngưỡng bằng curl ─────────────────────────────────────
stage_04_test_429() {
  stage "Test vượt ngưỡng — xác nhận 429 bằng curl"
  warn "DÙNG CURL, KHÔNG python-urllib — Cloudflare tự chặn User-Agent Python-urllib bằng 403 TRƯỚC KHI"
  warn "vào rule rate limit, nhìn y hệt lỗi khác và sẽ làm bạn tưởng rule sai."
  say "Payload dùng field botcheck (honeypot) — worker trả 200 ngay mà KHÔNG ghi Supabase, nên test"
  say "không tạo lead rác trong marketing_leads. An toàn để spam 12 request liên tiếp."
  say "Chạy loop dưới cho escape.myvivatour.com (đợi rule zone 1 đã Deploy ở stage 2 trước khi chạy):"
  note "for i in \$(seq 1 12); do curl -s -o /dev/null -w '%{http_code}\\n' -X POST \"$ESCAPE_URL\" \\"
  note "  -H 'Content-Type: application/json' -d '{\"email\":\"ratelimit-test@example.com\",\"botcheck\":\"x\"}'; sleep 1; done"
  say "Kỳ vọng: ~10 dòng đầu in 200, các dòng sau (11, 12...) in 429."
  step "Chạy loop trên trong 1 terminal khác (không phải terminal đang chạy wizard này)."
  confirm "Zone 1 (escape) có thấy 429 xuất hiện sau ~10 request?" && note "✓ zone 1 OK" || warn "zone 1 CHƯA thấy 429 — kiểm tra lại rule đã Deploy chưa, hoặc DNS/cache chưa propagate, thử lại sau vài phút."
  say "Lặp lại với zone 2 (dental), đổi URL:"
  note "for i in \$(seq 1 12); do curl -s -o /dev/null -w '%{http_code}\\n' -X POST \"$DENTAL_URL\" \\"
  note "  -H 'Content-Type: application/json' -d '{\"email\":\"ratelimit-test@example.com\",\"botcheck\":\"x\"}'; sleep 1; done"
  confirm "Zone 2 (dental) có thấy 429 xuất hiện sau ~10 request?" && note "✓ zone 2 OK" || warn "zone 2 CHƯA thấy 429 — kiểm tra lại rule zone 2 đã Deploy chưa."
}

# ── Stage 5: Test hồi quy — khách thật không bị chặn nhầm ───────────────────
stage_05_regression() {
  stage "Test hồi quy — submit form thật trên escape KHÔNG bị chặn nhầm"
  warn "Đợi ít nhất 1-2 phút sau stage 4 để cửa sổ rate-limit của IP bạn hết hạn trước khi test bước này —"
  warn "nếu test ngay, IP của bạn còn đang bị block do chính request test ở stage 4, sẽ ra false negative."
  open_url "$LP_FORM_URL"
  step "Điền form booking chính trên trang bằng data thật (không bật honeypot) → Submit MỘT lần."
  step "Xác nhận thấy thông báo thành công (không phải lỗi 429/network error)."
  step "Mở DevTools → tab Network → tìm request POST /api/lead vừa gửi → xác nhận status 200, không phải 429."
  confirm "Form submit thành công, status 200, không bị chặn nhầm?" && note "✓ hồi quy OK — khách thật không bị ảnh hưởng." || warn "Bị chặn nhầm! Có thể IP bạn vẫn còn trong cửa sổ block — đợi thêm rồi thử lại, hoặc hạ Duration của rule."
}

run_stage 1 "Bối cảnh & ngưỡng đã chốt"                stage_01_context
run_stage 2 "Zone 1: myvivatour.com"                    stage_02_zone_myvivatour
run_stage 3 "Zone 2: vietnamdentaltravel.com"           stage_03_zone_dental
run_stage 4 "Test vượt ngưỡng bằng curl (429)"          stage_04_test_429
run_stage 5 "Test hồi quy (form thật không bị chặn)"    stage_05_regression

finish
if [[ -f "$CF_RL_RESULT_FILE" ]]; then
  note "Kết quả cho NT1 đọc lại: $CF_RL_RESULT_FILE"
fi
note "Muốn chạy lại từ đầu (bỏ toàn bộ resume state): rm -f $CF_RL_STATE_FILE"
