#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Scope: GTM (GTM-TPQWV864) trigger+tag setup that consumes the dataLayer
# events landing pages already fire (docs/mvt-tracking-spec.md §2/§3/§6/§7),
# GA4 (G-2R0EJ2LBJ5) custom dimensions + Key event, and container PUBLISH.
# This wizard only tells you what to click — it never calls Google APIs and
# never needs credentials.
#
# Resume: progress is tracked in $GTM_STATE_FILE (default:
# .gtm-wizard-state, gitignored-safe dotfile in repo root). Re-running the
# script offers to skip any stage you already marked done. The GTM version ID
# from Publish is written to $GTM_RESULT_FILE (default: gtm-publish-result.txt)
# for NT1 to read back.

TOTAL_STAGES=13

GTM_STATE_FILE="${GTM_STATE_FILE:-.gtm-wizard-state}"
GTM_RESULT_FILE="${GTM_RESULT_FILE:-gtm-publish-result.txt}"

# _is_done ID — true if stage ID was previously marked complete.
_is_done() {
  [[ -f "$GTM_STATE_FILE" ]] && grep -qx "$1" "$GTM_STATE_FILE"
}

# _mark_done ID — record stage ID as complete (idempotent).
_mark_done() {
  touch "$GTM_STATE_FILE"
  _is_done "$1" || printf '%s\n' "$1" >> "$GTM_STATE_FILE"
}

# write_result KEY VALUE — upsert KEY=VALUE into GTM_RESULT_FILE. Separate
# from write_env/.env on purpose: this is a hand-off artifact for NT1, not a
# secret or local-dev config value.
write_result() {
  local key="$1" value="$2" tmp
  touch "$GTM_RESULT_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$GTM_RESULT_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$GTM_RESULT_FILE"
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$GTM_RESULT_FILE"
}

# run_stage ID "Title" fn — run stage fn unless already marked done (asks
# before re-running); offers to mark done afterwards so a re-run can resume
# past it. ID must be stable across edits (used as the resume key).
run_stage() {
  local id="$1" title="$2" fn="$3"
  if _is_done "$id"; then
    _clear
    printf '\n%s%s▸ Stage %s · %s %s(đã đánh dấu XONG lần trước)%s\n' \
      "$BOLD" "$BLUE" "$id" "$title" "$DIM" "$RESET"
    if ! confirm "Chạy lại stage này?"; then
      note "Bỏ qua — đã xong lần trước."
      return 0
    fi
  fi
  "$fn"
  if confirm "Đã hoàn tất '$title' trong GTM/GA4/Ads? (Y = đánh dấu xong để lần sau resume bỏ qua)"; then
    _mark_done "$id"
  else
    note "Chưa đánh dấu xong — lần chạy tới sẽ hỏi lại stage này."
  fi
}

GTM_URL="https://tagmanager.google.com/"
GA4_URL="https://analytics.google.com/"
ADS_URL="https://ads.google.com/aw/conversions"
LP_URL="https://escape.myvivatour.com/"

banner "GTM + GA4 setup cho MyVivaTour landing pages"
say "Container GTM-TPQWV864 · GA4 G-2R0EJ2LBJ5 · Ads AW-17709107883/Wq0ECKXBmfsbEKuVrvxB"
say "13 stage: tạo 5 trigger+tag, đăng ký custom dimension GA4, dọn trigger cũ,"
say "kiểm tra Ads không import trùng generate_lead, Preview QA, PUBLISH, verify production."
warn "KHÔNG import generate_lead từ GA4 sang Google Ads — chốt 260812, không bàn lại."

# ── Stage 1: Prerequisites & access ────────────────────────────────────────
stage_01_access() {
  stage "Chuẩn bị — mở 3 công cụ, xác nhận đăng nhập đúng tài khoản"
  say "Cần quyền Edit trên cả 3: GTM container GTM-TPQWV864, GA4 property G-2R0EJ2LBJ5, Ads account 572-470-7852."
  open_url "$GTM_URL"
  step "Trong Tag Manager, chọn Account/Container có Public ID = GTM-TPQWV864 (góc trên bên trái)."
  step "Mở workspace mặc định (Default Workspace)."
  open_url "$GA4_URL"
  step "Chọn đúng property có Measurement ID G-2R0EJ2LBJ5 (Admin → Data Streams để verify)."
  open_url "$ADS_URL"
  step "Xác nhận Customer ID hiển thị = 572-470-7852."
  pause "Đã mở đủ 3 tab và xác nhận đúng account/container/property?"
}

# ── Stage 2: Data Layer Variables ──────────────────────────────────────────
stage_02_dlv() {
  stage "GTM — tạo Data Layer Variable (DLV) cho params sẽ dùng ở tag"
  say "Các trigger ở §6 cần đọc param từ dataLayer. Tạo DLV trước, tag mới có cái để trỏ vào."
  say "Vào Variables (menu trái) → phần 'User-Defined Variables' → New."
  say "Với mỗi variable dưới: Variable Configuration → Data Layer Variable →"
  say "  Data Layer Variable Name = đúng tên cột dưới → Data Layer Version = Version 2 → Save."
  note "form_id          → tên DLV gợi ý: DLV - form_id"
  note "cta_text         → tên DLV gợi ý: DLV - cta_text"
  note "percent_scrolled → tên DLV gợi ý: DLV - percent_scrolled"
  note "popup_id         → tên DLV gợi ý: DLV - popup_id"
  note "(method của whatsapp_click là hằng số 'whatsapp' — set thẳng trong tag, KHÔNG cần DLV)"
  pause "Đã tạo đủ 4 Data Layer Variable trên?"
}

# ── Stage 3: form_success → generate_lead ──────────────────────────────────
stage_03_form_success() {
  stage "Trigger 'form_success' → GA4 tag 'generate_lead'"
  say "Trigger: Triggers → New → Trigger Configuration → Custom Event."
  step "Event name = form_success (chính xác, không regex) → Save trigger tên 'form_success'."
  say "Tag: Tags → New → Tag Configuration → Google Analytics: GA4 Event."
  step "Configuration Tag = GA4 config tag đo Measurement ID G-2R0EJ2LBJ5 (chọn tag config sẵn có,"
  step "  hoặc nếu chưa có Configuration Tag nào thì tạo GA4 Configuration mới với Measurement ID G-2R0EJ2LBJ5 trước)."
  step "Event Name = generate_lead"
  step "Event Parameters → add row: form_id = {{DLV - form_id}}"
  step "Triggering = trigger 'form_success' vừa tạo → Save tag tên 'GA4 - generate_lead'."
  pause "Đã tạo xong trigger form_success + tag GA4 - generate_lead?"
}

# ── Stage 4: cta_click → cta_click ─────────────────────────────────────────
stage_04_cta_click() {
  stage "Trigger 'cta_click' → GA4 tag 'cta_click'"
  step "Triggers → New → Custom Event → Event name = cta_click → Save trigger 'cta_click'."
  step "Tags → New → GA4 Event → Configuration Tag = GA4 config (G-2R0EJ2LBJ5)."
  step "Event Name = cta_click"
  step "Event Parameters → cta_text = {{DLV - cta_text}}"
  step "Triggering = trigger 'cta_click' → Save tag tên 'GA4 - cta_click'."
  pause "Đã tạo xong trigger cta_click + tag GA4 - cta_click?"
}

# ── Stage 5: whatsapp_click → contact ──────────────────────────────────────
stage_05_whatsapp_click() {
  stage "Trigger 'whatsapp_click' → GA4 tag 'contact'"
  step "Triggers → New → Custom Event → Event name = whatsapp_click → Save trigger 'whatsapp_click'."
  step "Tags → New → GA4 Event → Configuration Tag = GA4 config (G-2R0EJ2LBJ5)."
  step "Event Name = contact"
  step "Event Parameters → method = whatsapp  (giá trị CỐ ĐỊNH, gõ thẳng chữ 'whatsapp', không phải DLV)"
  step "Triggering = trigger 'whatsapp_click' → Save tag tên 'GA4 - contact (whatsapp)'."
  pause "Đã tạo xong trigger whatsapp_click + tag GA4 - contact?"
}

# ── Stage 6: scroll_depth → scroll_depth ───────────────────────────────────
stage_06_scroll_depth() {
  stage "Trigger 'scroll_depth' → GA4 tag 'scroll_depth'"
  step "Triggers → New → Custom Event → Event name = scroll_depth → Save trigger 'scroll_depth'."
  step "Tags → New → GA4 Event → Configuration Tag = GA4 config (G-2R0EJ2LBJ5)."
  step "Event Name = scroll_depth"
  step "Event Parameters → percent_scrolled = {{DLV - percent_scrolled}}"
  step "Triggering = trigger 'scroll_depth' → Save tag tên 'GA4 - scroll_depth'."
  pause "Đã tạo xong trigger scroll_depth + tag GA4 - scroll_depth?"
}

# ── Stage 7: popup_submit → popup_submit (một trigger cho cả 3 LP) ────────
stage_07_popup_submit() {
  stage "Trigger 'popup_submit' → GA4 tag 'popup_submit' (dùng chung escape+happytours+dental)"
  say "Chỉ MỘT trigger cho cả 3 LP — dental đã hợp nhất event này (260812), không tạo trigger riêng."
  say "Đây KHÔNG phải là conversion riêng — form_success (stage 3) đã là nguồn generate_lead duy nhất."
  say "popup_submit chỉ là tín hiệu ngữ cảnh 'lead này đến từ popup', đừng đánh dấu Key event cho nó."
  step "Triggers → New → Custom Event → Event name = popup_submit → Save trigger 'popup_submit'."
  step "Tags → New → GA4 Event → Configuration Tag = GA4 config (G-2R0EJ2LBJ5)."
  step "Event Name = popup_submit"
  step "Event Parameters → popup_id = {{DLV - popup_id}} ; form_id = {{DLV - form_id}}"
  step "Triggering = trigger 'popup_submit' → Save tag tên 'GA4 - popup_submit'."
  pause "Đã tạo xong trigger popup_submit + tag GA4 - popup_submit?"
}

# ── Stage 8: GA4 custom dimensions + Key event ─────────────────────────────
stage_08_ga4_dimensions() {
  stage "GA4 — đăng ký custom dimension + đánh dấu Key event"
  open_url "$GA4_URL"
  step "Admin (bánh răng góc dưới trái) → property G-2R0EJ2LBJ5 → Data display → Custom definitions."
  step "Create custom dimension x4, mỗi lần: Dimension name = tên param, Scope = Event,"
  step "  Event parameter = đúng tên param dưới đây → Save."
  note "form_id"
  note "cta_text"
  note "percent_scrolled"
  note "tour_id   (chưa có tag ở wizard này — đăng ký trước cho các event tour_* của happytours)"
  step "Admin → Events → tìm 'generate_lead' → bật toggle 'Mark as key event'."
  warn "generate_lead là Key event DUY NHẤT ăn theo lead thật — popup_submit KHÔNG được đánh dấu Key event."
  pause "Đã tạo 4 custom dimension + đánh dấu generate_lead là Key event?"
}

# ── Stage 9: dọn trigger cũ ─────────────────────────────────────────────────
stage_09_cleanup_old_trigger() {
  stage "Dọn — gỡ trigger cũ exit_popup_submit nếu còn"
  say "Dental đã bỏ event exit_popup_submit, hợp nhất về popup_submit (đã deploy). Nếu GTM còn trigger/tag"
  say "cũ tên exit_popup_submit thì đó là rác — gỡ để tránh nhầm khi đọc report sau này."
  step "Triggers → tìm 'exit_popup_submit' → nếu có: mở tag nào đang dùng nó, gỡ trigger khỏi tag đó"
  step "  (hoặc xoá tag nếu tag đó không dùng cho gì khác) → sau đó xoá trigger exit_popup_submit."
  note "Nếu không thấy trigger này trong danh sách → container đã sạch, bỏ qua stage này."
  pause "Đã kiểm tra và dọn xong (hoặc xác nhận không có gì để dọn)?"
}

# ── Stage 10: Ads — không import generate_lead từ GA4 ──────────────────────
stage_10_ads_no_import() {
  stage "Google Ads — xác nhận KHÔNG import generate_lead từ GA4"
  warn "CHỐT 260812 (Minh): gtag trực tiếp là nguồn conversion DUY NHẤT cho Ads."
  warn "KHÔNG import generate_lead từ GA4 sang Ads — kể cả dạng phụ (Secondary vẫn tính đếm đôi nếu bidding dùng)."
  open_url "$ADS_URL"
  step "Goals → Conversions → Summary → xem danh sách nguồn conversion."
  step "Tìm dòng nào Source = 'Google Analytics 4' và Event = generate_lead."
  step "Nếu THẤY dòng đó tồn tại:"
  step "  → mở dòng đó → Settings → đổi 'Include in Conversions' = Off (hoặc xoá import hẳn)."
  step "  → verify dòng conversion chính (label Wq0ECKXBmfsbEKuVrvxB, source = Website/gtag) vẫn"
  step "    'Include in Conversions' = On và đang được dùng cho bidding."
  note "Nếu KHÔNG thấy import GA4 nào trong danh sách → đã sạch, không cần làm gì thêm."
  pause "Đã xác nhận Ads không có import generate_lead nào tính vào bidding?"
}

# ── Stage 11: Preview mode QA ───────────────────────────────────────────────
stage_11_preview_qa() {
  stage "GTM Preview mode — QA từng event nổ đúng MỘT lần"
  warn "Preview KHÔNG phải live — tag chỉ chạy thật với khách sau khi Publish (stage 12)."
  say "Trong GTM workspace: nút Preview (góc trên phải) → nhập URL LP → Connect."
  ask LP_URL "URL landing page test (Enter = mặc định escape.myvivatour.com):"
  open_url "$LP_URL"
  step "Cửa sổ Tag Assistant mở kèm — để nguyên, thao tác trên tab LP:"
  step "  1. Click 1 nút CTA bất kỳ → Tag Assistant: tag GA4 - cta_click nổ đúng 1 lần."
  step "  2. Click icon WhatsApp nổi → tag GA4 - contact nổ đúng 1 lần."
  step "  3. Cuộn hết trang xuống đáy → tag GA4 - scroll_depth nổ ở mỗi mốc 25/50/75/90 (không nổ trùng)."
  step "  4. Điền và Submit form chính (dùng data test) → tag GA4 - generate_lead nổ đúng 1 lần."
  step "  5. Nếu LP có popup, trigger popup rồi submit → tag GA4 - popup_submit nổ đúng 1 lần."
  warn "Nếu bất kỳ tag nào nổ 0 lần hoặc >1 lần cho cùng một thao tác — DỪNG, đừng Publish, sửa trigger trước."
  pause "Đã thao tác đủ 5 bước và xác nhận mỗi tag nổ đúng một lần trong Tag Assistant?"
}

# ── Stage 12: Publish + ghi version ID ──────────────────────────────────────
stage_12_publish() {
  stage "PUBLISH container + ghi version ID"
  warn "Chỉ Publish sau khi stage 11 (Preview QA) đã sạch — Publish là live ngay lập tức cho mọi khách."
  say "Trong GTM workspace (không phải cửa sổ Preview): nút Submit (góc trên phải)."
  step "Version Name = ví dụ 'gtm-setup-260812 T4' ; Version Description = tóm tắt 5 trigger+tag vừa thêm."
  step "Publish."
  step "Sau khi publish xong, GTM mở trang chi tiết version — copy số Version ID (số nguyên, góc trên)."
  ask GTM_VERSION_ID "Nhập GTM Version ID vừa publish:"
  write_result "GTM_VERSION_ID" "$GTM_VERSION_ID"
  write_result "GTM_PUBLISHED_AT" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  pause "Đã publish và ghi version ID?"
}

# ── Stage 13: verify production ─────────────────────────────────────────────
stage_13_verify_production() {
  stage "Verify production — cửa sổ ẩn danh (KHÔNG nối Preview)"
  warn "Dùng cửa sổ Incognito/Private thật, KHÔNG phải tab đang nối GTM Preview ở stage 11."
  say "Mở incognito → vào $LP_URL → submit form chính bằng data test."
  open_url "$GA4_URL"
  step "GA4 → Reports → Realtime → chờ vài giây → xác nhận thấy event generate_lead xuất hiện."
  note "Đối chiếu thêm với docs/mvt-tracking-spec.md §7 (QA đầy đủ: Ads, Meta Test Events, Supabase row,"
  note "  network tab thấy cả web3forms + /api/lead) — phần đó là T5a (minhtest), không bắt buộc ở đây."
  pause "Đã thấy generate_lead trong GA4 Realtime từ cửa sổ incognito?"
}

run_stage 1  "Chuẩn bị & access"                          stage_01_access
run_stage 2  "Data Layer Variables"                        stage_02_dlv
run_stage 3  "form_success → generate_lead"                stage_03_form_success
run_stage 4  "cta_click → cta_click"                        stage_04_cta_click
run_stage 5  "whatsapp_click → contact"                     stage_05_whatsapp_click
run_stage 6  "scroll_depth → scroll_depth"                  stage_06_scroll_depth
run_stage 7  "popup_submit → popup_submit"                  stage_07_popup_submit
run_stage 8  "GA4 custom dimensions + Key event"            stage_08_ga4_dimensions
run_stage 9  "Dọn trigger cũ exit_popup_submit"              stage_09_cleanup_old_trigger
run_stage 10 "Ads — không import generate_lead từ GA4"       stage_10_ads_no_import
run_stage 11 "Preview mode QA"                               stage_11_preview_qa
run_stage 12 "Publish + ghi version ID"                      stage_12_publish
run_stage 13 "Verify production (incognito)"                 stage_13_verify_production

finish
if [[ -f "$GTM_RESULT_FILE" ]]; then
  note "Kết quả cho NT1 đọc lại: $GTM_RESULT_FILE"
fi
note "Muốn chạy lại từ đầu (bỏ toàn bộ resume state): rm -f $GTM_STATE_FILE"
